#!/usr/bin/bash

if [[ $# -eq 1 ]]; then

	#take first argument as path if it is longer than 9 chars
	INPUT_LEN=$(echo $1 | wc -c)
	if [[ "$INPUT_LEN" -gt 9 ]]; then
		selected=$1
	else
		# if anything else take current directory
		selected=$(pwd)
	fi

else
	MOST_WANTED=$(find ~/dotfiles ~/Downloads ~/Documents ~/Documents/coding ~/Documents/coding/golang ~/Documents/coding/playground ~/Documents/coding/vsCode/puppeteer/ ~/Documents/coding/algo/ ~/Documents/coding/algo/adventofcode ~/Documents/coding/algo/adventofcode/go/ ~/Documents/coding/fullstack/ -mindepth 0 -maxdepth 1 -type d)

	selected=$(
		printf "%s\n" "$MOST_WANTED" | fzf --preview 'tmux ls | grep --color=always -iC 50 "$(basename {})" || tmux ls' --prompt 'Most Wanted> ' \
			--header 'CTRL-A: All / CTRL-Z: Zoxide / CTRL-F: Most Wanted' \
			--bind "ctrl-z:change-prompt(Zoide> )+reload(zoxide query -l)" \
			--bind "ctrl-a:change-prompt(All> )+reload(fd -t d . "$HOME")" \
			--bind "ctrl-f:change-prompt(Most Wanted> )+reload(bash -c 'printf \"%s\n\" \"$MOST_WANTED\"')"
	)
fi

if [[ -z $selected ]]; then
	exit 0
fi

prefix_name=$(dirname "$selected" | tr '. ' _ | xargs basename)
name=$(basename "$selected" | tr '. ' _)
selected_name="$prefix_name-$name"
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s $selected_name -c $selected \; \
		send-keys 'vim .' C-m \; \
		new-window -c $selected -n cli \; \
		select-window -t 2
	tmux attach-session -t $selected_name
	exit 0
fi

if ! tmux has-session -t $selected_name 2>/dev/null; then
	tmux new-session -ds $selected_name -c $selected
	tmux send-keys -t $selected_name 'vim .' C-m
	tmux new-window -t $selected_name -c $selected -n cli
	tmux select-window -t $selected_name:2
fi

if [[ -z $TMUX ]]; then
	tmux attach-session -t $selected_name
else
	tmux switch-client -t $selected_name
fi
